### ISSUE TITLE
bind?

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/js-context-this#11]
Add bind?

**Comment by jrhorn424** [comment]
I think this is  worthwhile addition. It allows you to isolate your DOM manipulation code into objects and separate the registration of events from the handlers that are both encapsulated. I have some code examples from `006` if you want those.

**Comment by jrhorn424** [comment]
I believe it was the toggle hide functionality presented in the first volume of "Mastering Space and Time with JavaScript".

**Comment by RealWeeks** [comment]
@jrhorn424 I added bind with commit 6d612b1421a0e119ef2bff6912d554d3c7ef80af I'm going to close this.  Please open if you think it need elaboration.
