### ISSUE TITLE
Prefer function expression assignment to function declaration

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-context-this#15]
So this:

``` js
const goBoom = function () {
  console.log(this);
};
```

not this:

``` js
function goBoom () {
  console.log(this);
};
```

**Comment by payne-chris-r** [comment]
Is there any reason we might want to show them this so Ember convention doesn't look so different?

``` js
function goBoom () {
  console.log(this);
};
```

**Comment by jrhorn424** [comment]
@payne-chris-r That's not what we do in Ember?

Everything in Ember is modifying prototypes. What we do in Ember is actually:

``` js
// note the enclosing object
exports default Ember.Object.extend({
  goBoom () {
    console.log(this);
  },
});
```

**Comment by jrhorn424** [comment]
I'm in agreement with @gaand that these examples should change to expressions not declarations.
