### ISSUE TITLE
WAT

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-context-this#24]
``` js
function goBoom() {
    console.log(this);
};

let deathstar = {};
goBoom.call(deathstar);
// this === deathstar
```

**Context**: `this` refers to the passed object.  Here you would say "the
 object receives the method".

@gaand -- Why isn't it " Here you would say the method `call` receives the object as an argument"?

**Comment by gaand** [comment]
`call` is a method on `Function.prototype` that invokes the function, in this case `goBoom`, on which it is called with the object passed set to `this`, in this case `deathstar`.  So, it's equivalent to the following:

``` js
const goBoom = function () {
    console.log(this);
};

let deathstar = { goBoom };
deathstar.goBoom();
// this === deathstar
```

but without actually making `goBoom` a property of `deathstar`.

**Comment by payne-chris-r** [comment]
Ok. I understand, but I think that sentence might create more confusion than it removes...

**Comment by gaand** [comment]
I'm not arguing that point, and I'd be happy to see a different explanation (maybe something based on my response to your query?) I'm just trying to address your `WAT`

**Comment by raq929** [comment]
I would read this as, "Call the function goBoom with deathstar as the context (this)"

Are we trying to clarify the README?

**Comment by jrhorn424** [comment]
I'm more inclined toward @rts's wording than @payne-chris-r's at the moment.

**Comment by gaand** [comment]
@raq929's wording seems quite clear to me 🤖 .

**Comment by payne-chris-r** [comment]
Good. Than we're all in agreement. I like @rts' wording better too

**Comment by jrhorn424** [comment]
![](http://www.vomzi.com/wp-content/uploads/2016/01/new-everything-is-awesome-gif-222.gif)

**Comment by raq929** [comment]
This accidentally got reverted. 😞

**Comment by payne-chris-r** [comment]
I saw that! Noooo. #everythingIsNoLongerAwesome. But it can be again! #nextIteration.

**Comment by jrhorn424** [comment]
How did this reversion happen?

**Comment by raq929** [comment]
My fault; I copied and pasted some of Chris's code from his training branch
(or something like that), and I copied too much.
