### ISSUE TITLE
Replace this example / add more explanation

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-context-this#26]
This (haha) example uses `this` in two different ways, and is therefore confusing to beginners.
```javascript
function Counter() {
  this.sum = 0;
  this.count = 0;
}
Counter.prototype.add = function(array) {
  array.forEach(function(entry) {
    this.sum += entry;
    ++this.count;
    console.log(this);
  }, this);
  // ^---- Note
};

let obj = new Counter();
obj.add([2, 5, 9]);
obj.count
// 3
obj.sum
// 16
```

**Comment by gaand** [comment]
I'm not sure what you mean by "in two different ways".  The array iteration methods take an argument to set the value of `this` for the callback.  How it's being used here seems like a pattern to me.

**Comment by payne-chris-r** [comment]
@rts make sure you take a look at `014/master`. I pushed some code just recently that I think makes this example a little less confusing.
