### ISSUE TITLE
add a reference to the .call documentation?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-context-this#28]
What does `.call` take as an argument? An object. What is that object? The contextual object that we want to call the function on... I think taking a look at the documentation for `.call` may be helpful.

**Comment by jrhorn424** [comment]
A reference isn't enough. Visiting the documentation should be a part of the delivery, IMO.

**Comment by raq929** [comment]
Having the reference in the repo is the first step, though.

**Comment by jrhorn424** [comment]
You're not wrong. But, how much harder is it to wrap the link in a sentence and put it in the appropriate section as opposed to siloing it into the oft-ignored "Additional Resources" section?

**Comment by raq929** [comment]
Oh, I thought that's what he meant.
