### ISSUE TITLE
global_function.js - variables needs to be vars

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/js-context-this#35]
line 42: `showFullName (); // Peter Ally`
line 45: `window.showFullName (); // Peter Ally`

The comments that say `Peter Ally` suggests that that will be the output of those functions. However, that is untrue. The actual result is `undefined undefined`. At least half of the class was confused by those comments in WDI015.

**Comment by neugierige** [comment]
@raq929 says: this used to be run without `webpack`, and now it is. That may be the cause of the issue.

**Comment by neugierige** [comment]
UPDATE: `firstName` and `lastName` needs to be changed to `var`s in order for lines 42 and 45 to produce `Peter Ally`

**Comment by jrhorn424** [comment]
>@raq929 says: this used to be run without webpack, and now it is. That may be the cause of the issue.

Not likely.

> UPDATE: firstName and lastName needs to be changed to vars in order for lines 42 and 45 to produce Peter Ally

That seems like an appropriate fix, but not the right solution, if that makes sense.

To put it another way, if that's an actual fix, then the example should be reworked to use `let` and `const` appropriately.

**Comment by raq929** [comment]
Agreed. (This issue is weird because we were figuring it out in real time.)
So, basically, this example needs to be reworked. It was not a webpack issue, it was an updating to ES6 issue. And now the expected results in the file are not the actual results.

**Comment by raq929** [comment]
http://www.2ality.com/2015/02/es6-scoping.html

**Comment by raq929** [comment]
We have now updated all examples to ES6, so this is out of date.
