### ISSUE TITLE
Add constructor steps to Constructor Invocation Pattern

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-context-this#4]
`this` gets bound after new object creation. Add reference to how `new Function()` works:
1. new object created
2. Function called upon new object (`this` is set)
3. etc etc

**Comment by RealWeeks** [comment]
added notes detailing this after constructor section.

**Comment by jrhorn424** [comment]
@J-Weeks Would you please change it to this? The same list was included in `js-objects-constructors`.
1.  creates a new empty object (`{}`)
2.  attaches the constructor to the object as a property
3.  invokes the constructor function on the new object
4.  returns the object

**Comment by RealWeeks** [comment]
@jrhorn424 Can this be closed?

**Comment by jrhorn424** [comment]
Thanks @J-Weeks
